from datetime import datetime
from typing import Annotated, Literal

from pydantic import Field

from app.schemas.architect import LongText, ShortText
from app.schemas.base import Schema
from app.schemas.packaging import PackageManifest, ProjectPackage

DeploymentStatus = Literal["ready", "needs_configuration"]
RuntimeStatus = Literal["ready", "configuration_required", "not_ready"]
DeploymentAssetStatus = Literal["provided", "generated"]
HealthCheckStatus = Literal["generated", "unavailable"]
DeploymentTarget = Literal["frontend", "backend", "database"]


class DeploymentAsset(Schema):
    """One deployment overlay file, either supplied by the package or generated by Genesis."""

    file_path: ShortText
    status: DeploymentAssetStatus
    description: LongText
    content: LongText | None = None


class RuntimeRequirement(Schema):
    """One runtime prerequisite needed to deploy the generated project."""

    name: ShortText
    version: ShortText
    purpose: LongText


class DeploymentEnvironmentVariable(Schema):
    """A documented environment value required by the deployment overlay."""

    name: ShortText
    description: LongText
    example: ShortText
    required: bool = True


class HealthCheck(Schema):
    """Health endpoint information made available to the deployment runtime."""

    service: ShortText
    endpoint: ShortText | None = None
    status: HealthCheckStatus
    description: LongText


class DeploymentRecommendation(Schema):
    """Runtime-specific deployment advice for one web-application surface."""

    target: DeploymentTarget
    recommendation: LongText
    rationale: LongText


class DeploymentPlan(Schema):
    """Deployment-ready overlay and runtime summary derived from one project package revision."""

    deployment_id: ShortText
    package_id: ShortText
    created_at: datetime
    status: DeploymentStatus
    runtime_status: RuntimeStatus
    runtime_configuration_summary: LongText
    runtime_requirements: Annotated[list[RuntimeRequirement], Field(min_length=1, max_length=8)]
    required_environment_variables: Annotated[
        list[DeploymentEnvironmentVariable], Field(min_length=1, max_length=16)
    ]
    deployment_assets: Annotated[list[DeploymentAsset], Field(min_length=1, max_length=12)]
    health_checks: Annotated[list[HealthCheck], Field(min_length=1, max_length=4)]
    deployment_recommendations: Annotated[
        list[DeploymentRecommendation], Field(min_length=1, max_length=3)
    ]
    missing_configuration: Annotated[list[LongText], Field(max_length=16)]
    source_workspace_id: ShortText
    source_workspace_updated_at: datetime


class DeploymentGenerationRequest(Schema):
    """Existing package data consumed by deployment generation without modifying the package."""

    project_package: ProjectPackage
    package_manifest: PackageManifest
    package_included_files: Annotated[list[ShortText], Field(max_length=300)]
